import type { Metadata } from "next";
import "./globals.css";
import { Chatbot } from "@/components/Chatbot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
